export const projects = [
  {
    id: 0,
    title: "TravStay",
    date: "Nov 2024 - Dec 2024",
    description:
      "TravStay is a full-stack Website for booking and renting accommodations, allowing users to find and book properties easily and many more features.....",
    image: "../../public/projects/TravStay.png",
    tags: [
      "React Js",
      "Node Js",
      "MongoDB",
      "Express Js",
      "Bootstrap",
      "JWT Authentication",
      "Cloudinary",
      "Mapbox",
    ],
    category: "full-stack",
    webapp: "https://travstay-frontend-880v.onrender.com/",
  },
  {
    id: 1,
    title: "VirtualVista",
    date: "Sep 2024 - Oct 2024",
    description:
      "VirtualVista offers direct peer-to-peer video connections with instant messaging",
    image: "../../public/projects/video-call.png",
    tags: [
      "React Js",
      "Node Js",
      "Express Js",
      "Material-ui",
      "WebRTC",
      "Socket.io",
    ],
    category: "full-stack",
    webapp: "",
  },
  {
    id: 2,
    title: "MyPortfolio",
    date: "Jan 2025",
    description: "I have built and deployed a dynamic, animated portfolio website using Framer Motion and React.js to showcase my work. ",
    image: "../../public/projects/MyPortfolio.png",
    tags: ["React Js", "Framer Motion", "TalwindCSS", "EmailJS","Responsive"],
    category: "react",
    webapp: "",
  },
  {
    id: 3,
    title: "Zerodha",
    date: "Mar 2024 -April 2024",
    description: "I build fully-responsive zerodha clone",
    image: "../../public/projects/Zerodha-clone.png",
    tags: ["React Js", "Bootstrap"],
    category: "react",
    webapp: "",
  },
  {
    id: 4,
    title: "Quiz Time",
    date: "Nov-2023",
    description: "This is a quiz website which taught me how to use JavaScript features like setTimeout, clearInterval, and localStorage",
    image: "../../public/projects/Quiz-Time.png",
    tags: ["Html", "Css", "Javascript", "LocalStorage"],
    category: "javascript",
    webapp: "",
  },
  {
    id: 5,
    title: "Focus on Today",
    date: "Jan-2024",
    description: "Simple page build using HTML CSS JS,which helped me learn key JavaScript methods such as forEach, some,every and others for iteration ",
    image: "../../public/projects/FocusonToday.png",
    tags: ["Html", "Css", "Javascript"],
    category: "javascript",
    webapp: "",
  },
  {
    id: 6,
    title: "Simon Game",
    date: "Dec-2023",
    description:
      "Simon Game is a memory game where the player needs to memorize and repeat a sequence of lights and sounds. ",
    image: "../../public/projects/SimonGame.png",
    tags: ["Html", "Css", "Javascript"],
    category: "javascript",
    webapp: "",
  },
];

export const learnings = [
  "Learn front-end technologies like HTML, CSS, Bootstrap, JavaScript, React, Redux, and Tailwind CSS",
  "Learn How to make Responsive WebSite",
  "Learn about WebRTC, Sockets, AWS (basic), MVC Architecture (Model-View-Controller), and Passport.js for building real-time, scalable, and secure web applications.",
  "Learn how to use Backend technologies like Node.js and Express.js for building server-side applications.",
  "Learn how to work with databases like MongoDB and SQL (basic)",
  "Learn how to write clean code by using Prettier and Terminal commands",
  "Learn how to make production-ready code, deploy it on Render, and implement unit testing.",
  "Learn Version Control (Git),Github",
];
